server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ct
    username: root
    password: root
    platform: POSTGRESQL
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: true